### ISSUE TITLE
can't get this working python 2.7.11

### ISSUE THREAD

**Issue by jbruettcva** [nimbusscale/okta_aws_login#3]
running on python 2.7.11 on windows 8.1.  

getting the following error when i run: python C:\users\jbruett\desktop\okta_aws_login.py --configure

Traceback (most recent call last):
  File "C:\users\jbruett\desktop\okta_aws_login.py", line 12, in <module>
    from datetime import datetime, timezone, timedelta
ImportError: cannot import name timezone

Supporting Info:
> pip list
beautifulsoup4 (4.4.1)
boto3 (1.2.2)
botocore (1.3.11)
configparser (3.3.0.post2)
DateTime (4.0.1)
decorator (4.0.4)
docutils (0.12)
futures (2.2.0)
ipython (4.0.1)
ipython-genutils (0.1.0)
jmespath (0.9.0)
path.py (8.1.2)
pexpect (4.0.1)
pickleshare (0.5)
pip (7.1.2)
ptyprocess (0.5)
python-dateutil (2.4.2)
pytz (2015.7)
requests (2.8.1)
setuptools (18.2)
simplegeneric (0.8.1)
six (1.10.0)
traitlets (4.0.0)
wheel (0.24.0)
zope.interface (4.1.3)
(engineer)[32|12:00 PM|+734ms] [C:\jbtemp\ps]
> python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by nimbusscale** [comment]
As mentioned in the readme the tool is written in Python 3. Python 2 is not
supported.

**Comment by jbruettcva** [comment]
Thanks for the quick resposnse, I was unable to get my prereqs working in python 3.5.  I just reran without those prereqs, and it seemed to work as expected.
